#!/usr/bin/env bash
set -e # halt script on error

JEKYLL_ENV=develop bundle exec jekyll build --baseurl $BASEURL
bundle exec htmlproofer ./_site --internal-domains www.semi.technology --allow-hash-href --url-ignore "https://codepen.io" --empty-alt-ignore --assume-extension